# Use this open statement to create an OpenGL view:
/vis/open OGL 1000x1000-0+0
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
#/vis/viewer/set/viewpointThetaPhi 90 180 # x-section
/vis/viewer/set/viewpointThetaPhi 160 150 # perspective
#
# Specify zoom value:
/vis/viewer/zoom 4.0
#
# Prettify detector
/vis/geometry/set/visibility World 0 true
/vis/viewer/set/style surface
/vis/geometry/set/colour World 0 0.0 0.0 1.0 0.1 # Blue, 10% opaque
/vis/geometry/set/colour Detector 0 0.0 1.0 0.5 1.0 # Green, 100% opaque
/vis/geometry/set/colour Phantom 0 0.0 1.0 1.0 0.3 # Cyan, 30% opaque
/vis/geometry/set/colour Envelope 0 1.0 1.0 1.0 0.3 # White, 30% opaque
#
# Draw smooth trajectories
# Colour-coded by particle type
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ red
/vis/modeling/trajectories/drawByParticleID-0/set mu- pink
/vis/modeling/trajectories/drawByParticleID-0/set mu+ pink
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/set proton cyan
/vis/modeling/trajectories/drawByParticleID-0/set nu_e grey
#
# Turn on step points (or don't)
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
#
# Draw hits at end of event:
/vis/scene/add/hits
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# Set draw limit large for detectors with many crystals
/vis/ogl/set/displayListLimit 600000
#
# Set limit for events on screen (unlimited)
/vis/scene/endOfEventAction accumulate 1#-1
